// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_learn/test/mocks/data/api/pokemon_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_learn/data/api/response/pokemon.dart' as _i2;
import 'package:flutter_learn/data/api/schema/pokemon.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonListResponse_0 extends _i1.SmartFake
    implements _i2.PokemonListResponse {
  _FakePokemonListResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePokemonDetailResponse_1 extends _i1.SmartFake
    implements _i2.PokemonDetailResponse {
  _FakePokemonDetailResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonSchema].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonSchema extends _i1.Mock implements _i3.PokemonSchema {
  MockPokemonSchema() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PokemonListResponse> getPokemonList(
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonList,
          [
            limit,
            offset,
          ],
        ),
        returnValue: _i4.Future<_i2.PokemonListResponse>.value(
            _FakePokemonListResponse_0(
          this,
          Invocation.method(
            #getPokemonList,
            [
              limit,
              offset,
            ],
          ),
        )),
      ) as _i4.Future<_i2.PokemonListResponse>);
  @override
  _i4.Future<_i2.PokemonDetailResponse> getPokemonById(int? pokemonId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonById,
          [pokemonId],
        ),
        returnValue: _i4.Future<_i2.PokemonDetailResponse>.value(
            _FakePokemonDetailResponse_1(
          this,
          Invocation.method(
            #getPokemonById,
            [pokemonId],
          ),
        )),
      ) as _i4.Future<_i2.PokemonDetailResponse>);
}
